# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-26 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='img',
            field=models.CharField(max_length=150),
        ),
    ]
