# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0004_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='trackid',
            field=models.IntegerField(max_length=100),
        ),
    ]
