# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0005_auto_20210202_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='trackid',
            field=models.IntegerField(),
        ),
    ]
