# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-06 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0007_handletypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='handletypes',
            name='trackid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
