# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-06 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0009_pic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
