# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0010_pic_isdelete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='img',
        ),
        migrations.AddField(
            model_name='pic',
            name='ab_path',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pic',
            name='re_path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
