# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0011_auto_20210206_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='ab_path',
            new_name='abs_path',
        ),
        migrations.RenameField(
            model_name='pic',
            old_name='re_path',
            new_name='rel_path',
        ),
        migrations.AddField(
            model_name='pic',
            name='res_path',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
