# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0012_auto_20210206_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='yuan_id',
            field=models.CharField(default='x', max_length=20),
        ),
    ]
