# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-04-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0016_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='iscollect',
            field=models.BooleanField(default=False),
        ),
    ]
