# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-04-23 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0017_pic_iscollect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='yuan_id',
        ),
        migrations.AddField(
            model_name='pic',
            name='col_res_path',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
