# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-04-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0018_auto_20210423_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='col_res_path',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
