# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-04-23 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_img_enhancement', '0019_auto_20210423_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='col_res_path',
            new_name='ref_rel_path',
        ),
    ]
